blank_issues_enabled: false
contact_links:
  - name: Team Zypher
    url: https://theshashankk.guthub.com
    about: Please drop your doubts or queries there for an immediate response.
  - name: Owner
    url: https://t.me/Albertt_xD
    about: issue template owner.
